# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('holder', models.CharField(max_length=100)),
                ('intro', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('award', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='./Competition/images/')),
                ('result', models.FileField(upload_to='./Competition/result/')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('news', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='./Lecture/images/')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='tag',
            field=models.ManyToManyField(to='Main.Tag'),
        ),
        migrations.AddField(
            model_name='competition',
            name='tag',
            field=models.ManyToManyField(to='Main.Tag'),
        ),
    ]
