# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-16 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='image',
            field=models.ImageField(null=True, upload_to='./Competition/images/'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='result',
            field=models.FileField(null=True, upload_to='./Competition/result/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(null=True, upload_to='./Lecture/images/'),
        ),
    ]
