# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20171016_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
